# Generated by Django 5.2.15 on 2026-07-17 13:30

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='Imagem do pedido')),
            ],
            options={
                'verbose_name': 'imagem',
                'verbose_name_plural': 'imagens',
            },
        ),
        migrations.CreateModel(
            name='Pix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('chave', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'pix',
                'verbose_name_plural': 'pix',
            },
        ),
        migrations.CreateModel(
            name='Roupa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roupa', models.CharField(max_length=50, unique=True)),
                ('disponivel', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'roupa',
                'verbose_name_plural': 'roupas',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=50, unique=True)),
                ('disponivel', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'servico',
                'verbose_name_plural': 'servicos',
            },
        ),
        migrations.CreateModel(
            name='Tecido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecido', models.CharField(max_length=50, unique=True)),
                ('disponivel', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tecido',
                'verbose_name_plural': 'tecidos',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'administrador',
                'verbose_name_plural': 'administradores',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('telefone', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.TextField()),
                ('roupa', models.CharField(max_length=50)),
                ('tecido', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('data_criado_pedido', models.DateTimeField()),
                ('data_finalizado_pedido', models.DateTimeField()),
                ('forma_pagamento', models.CharField(default='', max_length=50)),
                ('preco', models.CharField(max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
            options={
                'verbose_name': 'relatório',
                'verbose_name_plural': 'relatórios',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField()),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, default='', null=True)),
                ('status', models.CharField(default='recebido', max_length=20)),
                ('atualizacao_status', models.DateTimeField(auto_now=True)),
                ('preco', models.CharField(default='', max_length=10)),
                ('forma_pagamento', models.CharField(default='', max_length=50)),
                ('pix_qrcode', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='Pix qrcode')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('img', models.ManyToManyField(to='core.imagempedido')),
                ('roupa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.roupa')),
                ('servico', models.ManyToManyField(to='core.servico')),
                ('tecido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tecido')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
            },
        ),
    ]
