# Generated by Django 5.2.15 on 2026-06-29 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roupa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roupa', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'roupa',
                'verbose_name_plural': 'roupas',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'servico',
                'verbose_name_plural': 'servicos',
            },
        ),
        migrations.CreateModel(
            name='Tecido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecido', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'tecido',
                'verbose_name_plural': 'tecidos',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(default='(xx) x-xxxxx-xxxx', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'administrador',
                'verbose_name_plural': 'administradores',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('telefone', models.CharField(default='(xx) x-xxxxx-xxxx', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField()),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, default='Nenhuma observação', null=True)),
                ('preco', models.CharField(default='A definir', max_length=15)),
                ('status', models.IntegerField(choices=[(1, 'Recebido'), (2, 'Em Andamento'), (3, 'Concluído'), (4, 'Cancelado')], default=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('roupa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.roupa')),
                ('servico', models.ManyToManyField(to='core.servico')),
                ('tecido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tecido')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
            },
        ),
    ]
