# Generated by Django 5.2.15 on 2026-06-30 15:35

import core.models
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', stdimage.models.StdImageField(blank=True, default=True, force_min_size=False, upload_to=core.models.get_file_path_pedido, variations={}, verbose_name='Imagem do pedido')),
            ],
            options={
                'verbose_name': 'imagem',
                'verbose_name_plural': 'imagens',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='img',
            field=models.ManyToManyField(to='core.imagempedido'),
        ),
    ]
