# Generated by Django 5.2.15 on 2026-07-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pix',
            name='tipo_chave',
        ),
        migrations.AddField(
            model_name='pix',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pix',
            name='chave',
            field=models.TextField(default=''),
        ),
    ]
