# Generated by Django 5.2.15 on 2026-07-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='forma_pagamento',
            field=models.CharField(default='', max_length=50),
        ),
    ]
