# Generated by Django 5.2.15 on 2026-07-16 18:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_relatorio_forma_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagempedido',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='Imagem do pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pix_qrcode',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='Pix qrcode'),
        ),
    ]
