# Generated by Django 5.2.15 on 2026-06-30 18:53

import core.models
import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imagempedido_pedido_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagempedido',
            name='img',
            field=stdimage.models.StdImageField(blank=True, default=None, force_min_size=False, null=True, upload_to=core.models.get_file_path_pedido, variations={}, verbose_name='Imagem do pedido'),
        ),
    ]
