# Generated by Django 5.2.15 on 2026-07-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='roupa',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tecido',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
