# Generated by Django 5.2.15 on 2026-07-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_imagempedido_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='telefone',
            field=models.CharField(default='(00) 00000-0000', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default='(00) 00000-0000', max_length=20),
        ),
    ]
