# Generated by Django 5.2.15 on 2026-07-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_roupa_disponivel_servico_disponivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='atualizacao_status',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
