# Generated by Django 5.2.15 on 2026-07-11 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pedido_atualizacao_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.TextField()),
                ('roupa', models.CharField(max_length=50)),
                ('tecido', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('data_criado_pedido', models.DateTimeField()),
                ('data_finalizado_pedido', models.DateTimeField()),
                ('preco', models.CharField(max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
            options={
                'verbose_name': 'relatório',
                'verbose_name_plural': 'relatórios',
            },
        ),
    ]
